# Generated by Django 3.2.5 on 2023-01-30 17:25

from django.db import migrations, models
import instaAPI.models


class Migration(migrations.Migration):

    dependencies = [
        ('instaAPI', '0002_auto_20230115_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='Data',
            field=models.JSONField(default=instaAPI.models.get_default_Play_Date),
        ),
        migrations.AlterField(
            model_name='post',
            name='Tag',
            field=models.JSONField(default=instaAPI.models.get_default_Post_Tag),
        ),
        migrations.AlterField(
            model_name='user',
            name='ProfileImg',
            field=models.ImageField(blank=True, upload_to='ProfileImg'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favData',
            field=models.JSONField(default=instaAPI.models.get_default_User_favDate),
        ),
        migrations.AlterField(
            model_name='user',
            name='intrestedPost',
            field=models.JSONField(default=instaAPI.models.get_default_User_interestedPost),
        ),
        migrations.AlterField(
            model_name='user',
            name='relationShip',
            field=models.JSONField(default=instaAPI.models.get_default_User_relationShip),
        ),
    ]
