# Generated by Django 4.1.6 on 2023-02-21 15:10

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instaAPI', '0006_auto_20230130_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='listenCount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='listenDay',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='musician',
            field=models.CharField(default=datetime.datetime(2023, 2, 21, 15, 10, 56, 404944, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='recent_artist',
            field=models.JSONField(default={'id': ''}),
        ),
        migrations.AddField(
            model_name='user',
            name='recent_music',
            field=models.JSONField(default={'id': ''}),
        ),
        migrations.AddField(
            model_name='user',
            name='recent_search',
            field=models.JSONField(default={'keyword': ''}),
        ),
    ]

