# Generated by Django 4.1.6 on 2023-02-21 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaAPI', '0007_playlist_listencount_playlist_listenday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='listenCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='listenDay',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 15, 18, 34, 17946, tzinfo=datetime.timezone.utc)),
        ),
    ]
